<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-88V4A8K" failures="13" tests="16" name="SeleniumProject04Apr" time="0.937" errors="0" timestamp="2025-05-23T07:30:59 IST">
  <testcase classname="tdd.TestNGAnnotations" name="checkNumber" time="0.022">
    <failure type="java.lang.AssertionError" message="This test case is failing.... expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This test case is failing.... expected [true] but found [false]
at tdd.TestNGAnnotations.checkNumber(TestNGAnnotations.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkNumber -->
  <testcase classname="tdd.TestNGAnnotations" name="compareObjects" time="0.002">
    <failure type="java.lang.AssertionError" message="expected not same [Java] but found [Java]">
      <![CDATA[java.lang.AssertionError: expected not same [Java] but found [Java]
at tdd.TestNGAnnotations.compareObjects(TestNGAnnotations.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- compareObjects -->
  <testcase classname="tdd.TestNGAnnotations" name="compareSumOfNumbers" time="0.033">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [20] but found [16]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [20] but found [16]
at tdd.TestNGAnnotations.compareSumOfNumbers(TestNGAnnotations.java:116)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- compareSumOfNumbers -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.038">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.021">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.055">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.017">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.003">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
at java.base@17.0.7/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:292)
at java.base@17.0.7/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
at java.base@17.0.7/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132)
at java.base@17.0.7/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
at java.base@17.0.7/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
at java.base@17.0.7/java.io.PrintStream.writeln(PrintStream.java:722)
at java.base@17.0.7/java.io.PrintStream.println(PrintStream.java:1028)
at app//tdd.TestNGAnnotations.contactUs(TestNGAnnotations.java:49)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.011">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.005">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.004">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.004"/>
  <testcase classname="tdd.TestNGAnnotations" name="contactUs" time="0.005">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method tdd.TestNGAnnotations.contactUs() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tdd.TestNGAnnotations.contactUs() didn't finish within the time-out 1
]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase classname="tdd.TestNGAnnotations" name="registration" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at tdd.TestNGAnnotations.registration(TestNGAnnotations.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- registration -->
  <testcase classname="tdd.TestNGAnnotations" name="login" time="0.002"/>
  <testcase classname="tdd.TestNGAnnotations" name="addToCart" time="0.0">
    <skipped/>
  </testcase> <!-- addToCart -->
</testsuite> <!-- SeleniumProject04Apr -->
